<?php

$nombre=$_POST["nomPerso"];
$apeP=$_POST["apePPerso"];
$apeM=$_POST["apeMPerso"];
$correo=$_POST["correoPerso"];
$contra=$_POST["contraPerso"];
$confiContra=$_POST["confiContraPerso"];
$cedula=$_POST["cedulaPerso"];
$telF=$_POST["telFPerso"];
$telM=$_POST["telMPerso"];
$fecha=$_POST["fechaNacPerso"];
$codigoP=$_POST["cpPerso"];
$calle=$_POST["callePerso"];
$colonia=$_POST["coloniaPerso"];
$ciudad=$_POST["ciudadPerso"];
$estado=$_POST["estadoPerso"];
$noCert=$_POST["noCert"];
$certifi=$_POST["nomCert"];
$orgCert=$_POST["orgCert"];
$fechaICert=$_POST["fechaICert"];
$fechaFCert=$_POST["fechaFCert"];
$gradoEst=$_POST["tipoGradoPerso"];
$pasantia=$_POST["opcion1"];
$empresaLab=$_POST["nomEmpPerso"];
$puestoEmp=$_POST["puestoEmpPerso"];
$correoEmp=$_POST["correoEmpPerso"];
$extTelFEmp=$_POST["ExtTelFEmp"];
$telFEmp=$_POST["telFEmpPerso"];
$funcionEmp=$_POST["funcionEmpPerso"];
$antecedentes=$_POST["opcion2"];
$veridicas=$_POST["opcion3"];
$avisos=$_POST["opcion4"];

echo $nombre;
echo $apeP;
echo $apeM;
echo $correo;
echo $contra;
echo $confiContra;
echo $cedula;
echo $telF;
echo $telM;
echo $fecha;
echo $codigoP;
echo $calle;
echo $colonia;
echo $ciudad;
echo $estado;
echo $noCert;
echo $certifi;
echo $orgCert;
echo $fechaICert;
echo $fechaFCert;
echo $gradoEst;
echo $pasantia;
echo $empresaLab;
echo $puestoEmp;
echo $correoEmp;
echo $extTelFEmp;
echo $telFEmp;
echo $funcionEmp;
echo $antecedentes;
echo $veridicas;
echo $avisos;

?>